"""Add payment fields to booking model

Revision ID: 002
Revises: 001
Create Date: 2024-06-07 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add payment-related columns to bookings table
    op.add_column('bookings', sa.Column('stripe_payment_intent_id', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('payment_status', sa.String(), nullable=True, server_default='unpaid'))
    op.add_column('bookings', sa.Column('payment_method', sa.String(), nullable=True))
    op.add_column('bookings', sa.Column('refund_amount', sa.Float(), nullable=True, server_default='0.0'))
    
    # Create unique constraint on stripe_payment_intent_id
    op.create_unique_constraint('uq_bookings_stripe_payment_intent_id', 'bookings', ['stripe_payment_intent_id'])
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop unique constraint
    op.drop_constraint('uq_bookings_stripe_payment_intent_id', 'bookings', type_='unique')
    
    # Remove payment-related columns from bookings table
    op.drop_column('bookings', 'refund_amount')
    op.drop_column('bookings', 'payment_method')
    op.drop_column('bookings', 'payment_status')
    op.drop_column('bookings', 'stripe_payment_intent_id')
    
    # ### end Alembic commands ### 